### ISSUE TITLE
Analyse: Tidsplan

### ISSUE THREAD

**Issue by Denpas404** [Denpas404/P3AngularMealPlanner#2]
Tidsplanen skal laves som et Gantt-chart. Arbejdet skal brydes ned i mindre stykker og der skal gives et estimat på hvor lang tid hver del tager. Derudover laves der en realiseret tidsplan, som kan sammenlignes med den estimerede tidsplan. Det vigtige ved sammenligningen er at få en bedre forståelse af, hvor lang tid forskellige ting tager, i forhold til hvor lang tid man tror det tager. Tidsplanen skal kunne printes på A3.

**Comment by jona339e** [comment]
https://drive.google.com/drive/folders/1lUFiWrExSowX2LsrcU7iOWRoY4bqLDXr

åben .gantt filer på https://www.onlinegantt.com/#/gantt
